baseURL = "https://fitnfunpro.com"
disableLanguages = []
disqusShortname = "fitnfunpro"
paginate = "6"
summaryLength = "10"
theme = "biztrox-hugo"
title = "Fitnfunpro"
[Languages.en]
contentDir = "content/english"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.ger]
contentDir = "content/german"
home = "Accueil"
languageCode = "ger-ger"
languageName = "ger"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "service"
name = "Service"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "team"
name = "Team"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[params]
author = "themefisher"
contact_form_action = "#"
description = "Airspace Hugo theme"
google_analitycs_id = "Your ID"
logo = "images/fitnfunpro-resize1.png"
logo_white = "images/fitnfunpro-resize1.png"
mail = "info@fitnfunpro.com"
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
mobile = "1234565523"
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
link = "contact"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate/animate.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
URL = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[[params.clients_logo_slider]]
link = "#"
logo = "images/client-logo/client-logo-1.png"
[[params.clients_logo_slider]]
link = "https://examplesite.com"
logo = "images/client-logo/client-logo-2.png"
[[params.clients_logo_slider]]
link = "#"
logo = "images/client-logo/client-logo-3.png"
[[params.clients_logo_slider]]
link = "https://examplesite.com"
logo = "images/client-logo/client-logo-4.png"
[[params.clients_logo_slider]]
link = "#"
logo = "images/client-logo/client-logo-5.png"
[[params.clients_logo_slider]]
link = "https://examplesite.com"
logo = "images/client-logo/client-logo-3.png"
[[params.contacts]]
icon = "ti-mobile"
[[params.contacts.contact]]
contact_item = "+971 50 688 7421"
[[params.contacts]]
icon = "ti-email"
[[params.contacts.contact]]
contact_item = "info@fitnfunpro.com"
[[params.contacts]]
icon = "ti-map-alt"
[[params.contacts.contact]]
contact_item = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
